language: ruby
rvm:
  - 2.1.2
  - 2.2.2
branches:
  only:
    - "master"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nanoc"
    template:
      - "%{repository}/%{branch} %{commit} %{author}: %{message}"
    use_notice: true
    skip_join: true
cache: bundler
sudo: false
git:
  depth: 10
